### ISSUE TITLE
Can't find the lib file under windows build

### ISSUE THREAD

**Issue by bigdimboom** [copperspice/cs_paint#3]
![image](https://user-images.githubusercontent.com/6119906/67105115-29c9f300-f196-11e9-9709-b60d928845fb.png)

**Comment by bgeller** [comment]
Can you let us know which version of Visual Studio you are using.  Do you have C++17 turned on?

**Comment by bigdimboom** [comment]
I'm using Visual Studio 2019.

**Comment by janwilmans** [comment]
Hi, I would like to look into your issue, can you tell me what commands you used to configure cmake?
please paste the commands use are using.

**Comment by bigdimboom** [comment]
PS C:\dev\cs_paint\build> cmake -G "Visual Studio 16 2019" -A x64 ..
-- The C compiler identification is MSVC 19.23.28106.4
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find sdl2 (missing: sdl2_DIR)
-- Found Vulkan: C:/VulkanSDK/1.1.114.0/Lib/vulkan-1.lib
-- GLM: Build with C++17 features
GLM: Visual C++ - MSVC compiler
-- The following packages have been found:

 * Vulkan, Required to build CsPaint, <https://vulkan.lunarg.com>

-- The following packages have not been found:

 * sdl2, Used only by the demo, <https://www.libsdl.org>

-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/cs_paint/build

**Comment by bigdimboom** [comment]
cmake version 3.15.1

**Comment by bigdimboom** [comment]
![image](https://user-images.githubusercontent.com/6119906/67456161-d45e6d80-f5fd-11e9-8e58-6049c91ad2ab.png)
![image](https://user-images.githubusercontent.com/6119906/67456185-e3452000-f5fd-11e9-8648-70cc9fc36ea5.png)

Install folder does not have any thing

**Comment by agserm** [comment]
I have finally been able to reproduce this issue, looking into it. Thanks for your report.

**Comment by agserm** [comment]
Can you try adding the line `set_target_properties(CsPaint PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS TRUE)`
at the end of `src/cspaint.cmake`.

Please let me know if this results in generating a `.lib` file.

**Comment by bigdimboom** [comment]
yeah, it's generating lib and dll now. Thanks

**Comment by agserm** [comment]
This change has been applied in 022dbd5, so this should now be resolved. Thank you for reporting this.
